# Generated by Django 6.0.4 on 2026-04-13 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. '15°' or '1:4'", max_length=50)),
                ('pitch_factor', models.DecimalField(decimal_places=4, help_text='Multiply plan area by this factor to get rafter lineal metres.', max_digits=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_reference', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('site_address', models.TextField()),
                ('status', models.CharField(choices=[('estimate', 'Estimate'), ('drawing_uploaded', 'Drawing Uploaded'), ('order_placed', 'Order Placed')], default='estimate', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('freight_surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_uploads', to='jobs.job')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Unit 1 Midfloor'", max_length=200)),
                ('system_type', models.CharField(choices=[('midfloor', 'Midfloor'), ('roof', 'Roof')], max_length=10)),
                ('include_boundary_joists', models.BooleanField(default=True)),
                ('boundary_perimeter_lm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('include_stair_void_trimmers', models.BooleanField(default=False)),
                ('calculated_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('member_schedule', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary_joist_product', models.ForeignKey(blank=True, limit_choices_to={'product_use': 'boundary_joist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_joist_sub_jobs', to='products.product')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_jobs', to='jobs.job')),
                ('roof_pitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_jobs', to='jobs.roofpitch')),
                ('stair_void_trimmer_product', models.ForeignKey(blank=True, limit_choices_to={'product_use': 'stair_void_trimmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair_void_sub_jobs', to='products.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloorRoofArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_label', models.CharField(blank=True, max_length=200)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joist_spacing', models.CharField(choices=[('0.400', '400 c/c'), ('0.450', '450 c/c'), ('0.600', '600 c/c')], max_length=5)),
                ('joist_product', models.ForeignKey(limit_choices_to={'product_use': 'joist_rafter'}, on_delete=django.db.models.deletion.PROTECT, related_name='floor_roof_areas', to='products.product')),
                ('sub_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='jobs.subjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalBeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(limit_choices_to={'product_use': 'beam'}, on_delete=django.db.models.deletion.PROTECT, related_name='additional_beam_lines', to='products.product')),
                ('sub_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_beams', to='jobs.subjob')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
