# Generated by Django 6.0.4 on 2026-04-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('products', '0002_remove_product_use_add_use_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbeam',
            name='product_description',
            field=models.CharField(blank=True, help_text='e.g. LVL11 360x63 or Glulam 315x90', max_length=200),
        ),
        migrations.AddField(
            model_name='floorroofarea',
            name='product_description',
            field=models.CharField(blank=True, help_text='e.g. LIB240.88 I-Joist or LVL11 240x45', max_length=200),
        ),
        migrations.AddField(
            model_name='subjob',
            name='boundary_joist_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subjob',
            name='stair_void_trimmer_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='additionalbeam',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_beam': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_beam_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='floorroofarea',
            name='joist_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_joist_rafter': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_roof_areas', to='products.product'),
        ),
        migrations.AlterField(
            model_name='subjob',
            name='boundary_joist_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_boundary_joist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_joist_sub_jobs', to='products.product'),
        ),
        migrations.AlterField(
            model_name='subjob',
            name='stair_void_trimmer_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_stair_void_trimmer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair_void_sub_jobs', to='products.product'),
        ),
    ]
