# Generated by Django 6.0.4 on 2026-04-17 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roofpitch'),
        ('jobs', '0006_rename_subjob_to_section'),
        ('products', '0004_alter_pricebook_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['created_at'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterField(
            model_name='section',
            name='boundary_joist_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_boundary_joist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_joist_sections', to='products.product'),
        ),
        migrations.AlterField(
            model_name='section',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='section',
            name='roof_pitch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.roofpitch'),
        ),
        migrations.AlterField(
            model_name='section',
            name='stair_void_trimmer_product',
            field=models.ForeignKey(blank=True, limit_choices_to={'use_as_stair_void_trimmer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stair_void_sections', to='products.product'),
        ),
    ]
