# Generated by Django 6.0.4 on 2026-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_hardware_allowance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estimate', 'verbose_name_plural': 'Estimates'},
        ),
        migrations.AlterField(
            model_name='section',
            name='system_type',
            field=models.CharField(choices=[('midfloor', 'Midfloor'), ('roof', 'Roof'), ('other', 'Other')], max_length=10),
        ),
    ]
