# Generated by Django 6.0.4 on 2026-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_options_alter_section_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimate_uncertainty_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override estimate uncertainty band %. Leave blank to use the global default.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='wastage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override wastage %. Leave blank to use the global default.', max_digits=5, null=True),
        ),
    ]
