# Generated by Django 6.0.4 on 2026-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_per_estimate_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='label',
            field=models.CharField(blank=True, default='Untitled Estimate', help_text="Optional label to distinguish multiple estimates on the same project, e.g. 'Option A'.", max_length=100),
        ),
    ]
