# Generated by Django 6.0.4 on 2026-08-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlist', '0004_cutlistproject_finalize'),
        ('jobs', '0014_alter_job_label'),
        ('products', '0008_alter_pricebookentry_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_cutlist',
            field=models.ForeignKey(blank=True, help_text='Set when this estimate was created from a cutlist stock order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_jobs', to='cutlist.cutlistproject'),
        ),
        migrations.CreateModel(
            name='CutlistImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutlist_import_lines', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutlist_import_lines', to='jobs.section')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
