# Generated by Django 6.0.4 on 2026-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_source_cutlist_cutlistimportline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutlistimportline',
            name='tab_index',
            field=models.PositiveIntegerField(blank=True, help_text='Index into the source cutlist state.tabs[] this line was mapped from — used to join back to the per-stick stock order for display.', null=True),
        ),
    ]
