# Generated by Django 6.0.4 on 2026-08-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_cutlistimportline_tab_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutlistimportline',
            name='product_description',
            field=models.CharField(blank=True, help_text='Raw member name from the cutlist, kept as a placeholder label when no product was matched.', max_length=200),
        ),
    ]
