# Generated by Django 6.0.4 on 2026-09-03 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_cutlistimportline_product_description'),
        ('products', '0011_product_cover_mm_product_use_as_cladding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='system_type',
            field=models.CharField(choices=[('midfloor', 'Midfloor'), ('roof', 'Roof'), ('other', 'Other'), ('cladding', 'Cladding')], max_length=10),
        ),
        migrations.CreateModel(
            name='CladdingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_label', models.CharField(blank=True, max_length=200)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cladding_product', models.ForeignKey(blank=True, limit_choices_to={'use_as_cladding': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_areas', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cladding_areas', to='jobs.section')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
