# Generated by Django 6.0.4 on 2026-09-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlist', '0005_memberproductmapping'),
        ('jobs', '0020_remove_section_roof_pitch_floorroofarea_roof_pitch'),
        ('products', '0014_seed_cladding_stock_lengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claddingarea',
            name='area_m2',
        ),
        migrations.AddField(
            model_name='claddingarea',
            name='height_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claddingarea',
            name='orientation',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=10),
        ),
        migrations.AddField(
            model_name='claddingarea',
            name='width_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cladding_cutlist',
            field=models.ForeignKey(blank=True, help_text="Cutlist generated from this cladding job's own vertical elevations, if any. Opposite direction to source_cutlist: this job produced that cutlist, rather than being created from one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_source_jobs', to='cutlist.cutlistproject'),
        ),
        migrations.AddField(
            model_name='job',
            name='stock_contingency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override cutlist stock contingency %. Leave blank to use the global default.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CladdingCutlistLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(blank=True, help_text='Raw member name from the cutlist, kept as a placeholder label when no product was matched.', max_length=200)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cladding_cutlist_lines', to='jobs.job')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_cutlist_lines', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
