# Generated by Django 6.0.4 on 2026-09-09 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_remove_claddingarea_area_m2_claddingarea_height_m_and_more'),
        ('products', '0014_seed_cladding_stock_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='CladdingExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(blank=True, help_text='e.g. Vertica Scriber 40x19 or Corner Mould', max_length=200)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cladding_extra_items', to='jobs.job')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_extra_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
