# Generated by Django 6.0.4 on 2026-09-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlist', '0005_memberproductmapping'),
        ('jobs', '0022_claddingextraitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['created_at'], 'verbose_name': 'part', 'verbose_name_plural': 'parts'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='hardware_allowance_amount',
        ),
        migrations.AddField(
            model_name='claddingarea',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_areas', to='jobs.section'),
        ),
        migrations.AddField(
            model_name='claddingcutlistline',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_cutlist_lines', to='jobs.section'),
        ),
        migrations.AddField(
            model_name='claddingextraitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_extra_items', to='jobs.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='cladding_cutlist',
            field=models.ForeignKey(blank=True, help_text="Cutlist generated from this part's own vertical elevations, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_source_sections', to='cutlist.cutlistproject'),
        ),
        migrations.AddField(
            model_name='section',
            name='hardware_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='hardware_allowance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override hardware allowance % for this part. Leave blank to use the job default.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='stock_contingency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override cutlist stock contingency % for this part (cladding only). Leave blank to use the global default.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='wastage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override wastage % for this part. Leave blank to use the job default.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='claddingarea',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_legacy_cladding_areas', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='claddingcutlistline',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_legacy_cladding_cutlist_lines', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='claddingextraitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_legacy_cladding_extra_items', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cladding_cutlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cladding_source_jobs', to='cutlist.cutlistproject'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hardware_allowance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default hardware allowance % for new Parts. Leave blank to use the global default. Each Part can override this individually.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stock_contingency_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='wastage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default wastage % for new Parts. Leave blank to use the global default. Each Part can override this individually.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='system_type',
            field=models.CharField(choices=[('midfloor', 'Midfloor'), ('roof', 'Roof'), ('other', 'Other'), ('cladding', 'Cladding')], max_length=10),
        ),
    ]
