# Generated by Django 6.0.4 on 2026-09-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_cladding_to_section_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claddingarea',
            name='job',
        ),
        migrations.RemoveField(
            model_name='claddingcutlistline',
            name='job',
        ),
        migrations.RemoveField(
            model_name='claddingextraitem',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='calculated_subtotal',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cladding_cutlist',
        ),
        migrations.RemoveField(
            model_name='job',
            name='member_schedule',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stock_contingency_pct',
        ),
        migrations.AlterField(
            model_name='claddingarea',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_areas', to='jobs.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claddingcutlistline',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_cutlist_lines', to='jobs.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claddingextraitem',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cladding_extra_items', to='jobs.section'),
            preserve_default=False,
        ),
    ]
