# Generated by Django 6.0.4 on 2026-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_claddingarea_low_high_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claddingarea',
            name='high_height_m',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='claddingarea',
            name='low_height_m',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='claddingarea',
            name='width_m',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
