# Generated by Django 6.0.4 on 2026-09-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_claddingarea_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='claddingcutlistline',
            name='contingency_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
