# Generated by Django 6.0.4 on 2026-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_claddingcutlistline_contingency_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visible_to_merchant',
            field=models.BooleanField(default=False, help_text='LB staff always see every estimate. An estimate an LB user creates stays hidden from the merchant until explicitly shown here; one the merchant creates themselves is visible by default.'),
        ),
    ]
