# Generated by Django 6.0.4 on 2026-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('drawing', 'Drawing'), ('design', 'Design File'), ('quote', 'Quote'), ('revit_export', 'Revit Export'), ('estimate_report', 'Estimate Report'), ('other', 'Other')], default='drawing', max_length=20),
        ),
    ]
