# Generated by Django 6.0.4 on 2026-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_threshold', models.DecimalField(decimal_places=2, default=1000.0, help_text='Job total below this value attracts the fixed freight fee.', max_digits=10)),
                ('fixed_freight_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee applied to orders below the freight threshold.', max_digits=10)),
                ('surcharge_enabled', models.BooleanField(default=False, help_text='System-wide toggle for the fuel surcharge.')),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage surcharge applied to qualifying order totals when enabled.', max_digits=5)),
                ('stair_void_trimmer_allowance_lm', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard lineal metre allowance applied when the stair void trimmer toggle is on.', max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Freight Settings',
                'verbose_name_plural': 'Freight Settings',
            },
        ),
    ]
