# Generated by Django 6.0.4 on 2026-06-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_freightsettings_estimate_uncertainty_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used in templates: {% help_trigger 'this-slug' %}", unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML displayed in the help panel. Supports bold, lists, links, etc.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Help Topic',
                'verbose_name_plural': 'Help Topics',
                'ordering': ['sort_order', 'slug'],
            },
        ),
    ]
