# Generated by Django 6.0.4 on 2026-07-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_helptopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightsettings',
            name='wastage_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Wastage % applied to all lineal metre quantities. Accounts for off-cuts when cutting from discrete stock lengths (typical: 5–15%).', max_digits=5),
        ),
    ]
