# Generated by Django 6.0.4 on 2026-09-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_stairvoidsettings_into_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
    ]
