# Generated by Django 6.0.4 on 2026-09-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='stock_contingency_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Default contingency % added on top of an optimised cutlist's real stock quantity, for on-site mis-cuts or breakage (typical: 10–15%). Individual estimates can override this.", max_digits=5),
        ),
    ]
