# Generated by Django 6.0.4 on 2026-05-21 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organisation_price_book'),
        ('jobs', '0007_alter_section_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CutlistProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Cutlist', max_length=100)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutlist_projects', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutlist_projects', to='jobs.job')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutlist_projects', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
