# Generated by Django 6.0.4 on 2026-08-31 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlist', '0004_cutlistproject_finalize'),
        ('products', '0008_alter_pricebookentry_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=100, unique=True)),
                ('raw_name', models.CharField(help_text='Most recent raw text this was set from (for display only).', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_mappings', to='products.product')),
            ],
            options={
                'ordering': ['raw_name'],
            },
        ),
    ]
