# Generated by Django 6.0.4 on 2026-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlist', '0005_memberproductmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutlistproject',
            name='visible_to_merchant',
            field=models.BooleanField(default=False, help_text='LB staff always see every cutlist. Mirrors jobs.Job.visible_to_merchant — hidden by default when created by an LB user, visible by default when created by the merchant themselves.'),
        ),
    ]
