# Generated by Django 6.0.4 on 2026-04-13 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('i_joist', 'I-Joist'), ('lvl', 'LVL'), ('glulam', 'Glulam')], max_length=20)),
                ('product_use', models.CharField(choices=[('joist_rafter', 'Joist / Rafter'), ('boundary_joist', 'Boundary Joist'), ('stair_void_trimmer', 'Stair Void Trimmer'), ('beam', 'Beam')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['product_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_book', to='accounts.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_lm', models.DecimalField(decimal_places=4, help_text='Wholesale price per lineal metre, ex GST.', max_digits=10)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='products.pricebook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='products.product')),
            ],
            options={
                'ordering': ['product__product_type', 'product__name'],
                'unique_together': {('price_book', 'product')},
            },
        ),
    ]
