# Generated by Django 6.0.4 on 2026-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_use',
        ),
        migrations.AddField(
            model_name='product',
            name='use_as_beam',
            field=models.BooleanField(default=False, verbose_name='Beam'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_as_boundary_joist',
            field=models.BooleanField(default=False, verbose_name='Boundary Joist'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_as_joist_rafter',
            field=models.BooleanField(default=False, verbose_name='Joist / Rafter'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_as_stair_void_trimmer',
            field=models.BooleanField(default=False, verbose_name='Stair Void Trimmer'),
        ),
    ]
