# Generated by Django 6.0.4 on 2026-04-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricebook_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
