# Generated by Django 6.0.4 on 2026-08-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producttype_finalize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricebookentry',
            options={'ordering': ['product__product_type__sort_order', 'product__product_type__name', 'product__name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type__sort_order', 'product_type__name', 'sort_order', 'name']},
        ),
    ]
