# Generated by Django 6.0.4 on 2026-08-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_pricebookentry_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimberTypeDefaultStockLengths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timber_type', models.CharField(choices=[('LIB', 'I-Beam / LIB'), ('LVL8', 'LVL8'), ('LVL11', 'LVL11'), ('LVL13', 'LVL13'), ('GL', 'Glulam'), ('OTHER', 'Other')], max_length=10, unique=True)),
                ('stock_lengths', models.CharField(help_text='Comma-separated stock lengths in mm (e.g. "7200, 6000, 5400, 4800, 3600").', max_length=200)),
            ],
            options={
                'verbose_name': 'Timber Type Default Stock Lengths',
                'verbose_name_plural': 'Timber Type Default Stock Lengths',
                'ordering': ['timber_type'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stock_lengths',
            field=models.CharField(blank=True, help_text='Comma-separated stock lengths available for this product, in mm (e.g. "7200, 6000, 5400, 4800, 3600"). Used as the Cutlist Optimizer\'s default stock list when a cutlist member is linked to this product. Leave blank to fall back to the generic default for this product\'s timber type.', max_length=200),
        ),
    ]
