# Generated by Django 6.0.4 on 2026-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_seed_default_stock_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Cladding cover width in mm once lapped/jointed — the estimator divides area by this to get lineal metres. Only relevant for products used as Cladding.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_as_cladding',
            field=models.BooleanField(default=False, verbose_name='Cladding'),
        ),
    ]
