# Generated by Django 6.0.4 on 2026-09-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_seed_cladding_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timbertypedefaultstocklengths',
            name='timber_type',
            field=models.CharField(choices=[('LIB', 'I-Beam / LIB'), ('LVL8', 'LVL8'), ('LVL11', 'LVL11'), ('LVL13', 'LVL13'), ('GL', 'Glulam'), ('CLADDING', 'Cladding'), ('OTHER', 'Other')], max_length=10, unique=True),
        ),
    ]
