# Generated by Django 6.0.4 on 2026-09-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_seed_cladding_stock_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('lm', 'Lineal Metre'), ('each', 'Each')], default='lm', help_text='How this product is priced — per lineal metre (the default) or per piece (e.g. scribers, fixings). Only affects Additional Beams and Cladding Extra Items — every other calculation derives its lineal metres from area/spacing and has no independent piece count to price "each" against.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='price_per_lm',
            field=models.DecimalField(decimal_places=4, help_text='Wholesale price, ex GST — per lineal metre, or per piece if the product\'s unit of measure is "Each".', max_digits=10),
        ),
    ]
